#!/usr/bin/env bash

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
exec "$SCRIPT_DIR/src/backend/slimerjs/slimerjs" "$SCRIPT_DIR/src/backend/slimerjs/run-analyzer.js" $@
